### ISSUE TITLE
p. 35 pirate book

### ISSUE THREAD

**Issue by Eva-biostat** [ndphillips/ThePiratesGuideToR#24]
aggregate function does not need "formula =" :
aggregate(age ~ sex,
          data = pirates,
          FUN = mean, na.rm=TRUE)

Error in aggregate.formula(formula = age ~ sex, data = pirates, FUN = mean,  : 
  argument 'x' is  missing -- it has been renamed from 'formula'

**Comment by Eva-biostat** [comment]
Section 3.6:
"It looks like we got a Bayes factor of 0.12 which is strong evidence for the null hypothesis"
It is like proving the sea exists vs. having sufficient evidence that land is real. The sea is a fallback, it is always there, everywhere. Rather, there "is not sufficient evidence for alternative hypothesis" (i.e., that pirate age affects choice of headband).

**Comment by ndphillips** [comment]
The `aggregate(formula` issue should now be fixed.

For your second comment @Eva-biostat , can you help clarify? It's been a while since I've interpreted a Bayes Factor but my best recollection is that a small Bayes Factor, such as around or less than 1/10 is considered strong evidence for the Null hypothesis. 

Again it's been a while for me, but here's what popped up on Google: https://tellmi.psy.lmu.de/felix/BFDA_app/#:~:text=If%20a%20Bayes%20factor%20is,evidence%20for%20the%20null%20hypothesis.

**Comment by Eva-biostat** [comment]
Hi Nathan, it is great to hear from you! I do not remember the comment, but I just have to say that I am very fond of your book! I have such pleasant memories connected with it. A year ago, I was reading it on the porch of a small vacation house in Florida. The owner had a small red dog named Tito and a swimming pool. I also liked your explanation of the p-value, something about the sea, again I do not remember exactly...
Have a great day,
Eva
________________________________

**Comment by ndphillips** [comment]
Thanks for the positive feedback Eva! I'll go ahead and close this issue.

**Comment by Eva-biostat** [comment]
[like]  Zadorozny, Eva Vladi reacted to your message:
________________________________
